# Site settings
title: Diki Andriansyah Blog - Stay Brom
email: diki1aap@gmail.com
description: "Ini sebuah blog room Diki Andriansyah yang saya kelola untuk membagikan tulisan dan aktivitas saya, seperti pengetahuan, pengamatan dan informasi di penulisan kode."
baseurl: ""
url: "https://dikiaap.github.io"
subtitle: Brom brom code brom !!
keywords: "Diki Andriansyah, Diki Andriansyah Blog, dikiaap, Diki Andriansyah Ananta Putra"
sosial_username: dikiaap
simple_search: http://google.com/search
# Build settings
markdown: kramdown
author: dikiaap
permalink: "write/:year/:month/:day/:title/"
paginate: 5
paginate_path: "/page/:num/"
gems:
  - jekyll-paginate