# Site settings
title: martyn.pw
email: martijn.rondeel@windesheim.nl
description: "Personal website of Martijn Rondeel"
url: "https://martyn.pw"
keywords: "martijn rondeel, martyn.pw, personal blog, website, programming, experiments, web development"
simple_search: http://google.com/search
# Build settings
markdown: kramdown
author: Martyn96
permalink: "blog/:title/"
paginate: 4
paginate_path: "/page/:num/"
gems:
  - jekyll-paginate
# Minify compiled sass
sass:
  style: compressed
