name: CI

on: [push]

jobs:
  lint:
    name: Lint

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Read .nvmrc
      run: echo ::set-output name=NVMRC::$(cat .nvmrc)
      id: nvm

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '${{ steps.nvm.outputs.NVMRC }}'

    - name: Install dependencies
      run: yarn --frozen-lockfile

    - name: Lint
      run: yarn lint
